Version 3.5.0

diff --git a/source/usr/bin/check_hotplug_usage b/source/usr/bin/check_hotplug_usage
--- a/source/usr/bin/check_hotplug_usage
+++ b/source/usr/bin/check_hotplug_usage
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-# Copyright (C) 2021 Charles Atkinson
+# Copyright (C) 2023 Charles Atkinson
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -60,8 +60,20 @@ source "$BUNG_LIB_DIR/version.scrippet" || exit 1
 #    |   +-- usage
 #    |   |
 #    |   +-- parse_conf
+#    |   |   |
+#    |   |   +-- ...
+#    |   |   |
+#    |   |   +-- parse_conf_checkhotplugusage
+#    |   |
+#    |   +-- postprocess_email_for_report
 #    |   |
 #    |   +-- err_trap_email_for_report
+#    |   |
+#    |   +-- postprocess_checkhotplugusage_conf
+#    |   |
+#    |   +-- err_trap_checkhotplugusage_conf
+#    |   |
+#    |   +-- postprocess_org_name_conf
 #    |   |
 #    |   +-- err_trap_post_hook_conf
 #    |   |
@@ -73,10 +85,13 @@ source "$BUNG_LIB_DIR/version.scrippet" || exit 1
 #    |   |
 #    |   +-- do_pid
 #    |
-#    +-- run_subsidiary_scripts
+#    +-- run_pre_hooks
+#    |
+#    +-- ck_hotplug_usage
 #    |
 #    +-- finalise
 #
+
 # Utility functions called from various places:
 #     ck_file ck_uint err_trap_uint fct msg
 
@@ -85,6 +100,7 @@ source "$BUNG_LIB_DIR/version.scrippet" || exit 1
 source "$BUNG_LIB_DIR/ck_file.fun" || exit 1
 source "$BUNG_LIB_DIR/ck_uint.fun" || exit 1
 source "$BUNG_LIB_DIR/do_pid.fun" || exit 1
+source "$BUNG_LIB_DIR/do_umounts.fun" || exit 1    # Needed for function finalise
 source "$BUNG_LIB_DIR/err_trap_uint.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_email_for_report.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_post_hook_conf.fun" || exit 1
@@ -113,7 +129,8 @@ function initialise {
     
     # Parse configuration file
     # ~~~~~~~~~~~~~~~~~~~~~~~~
-    emsg=
+    maxbackupage=3
+    maxdevicechangedays=3
     # Note: ensure a space on both sides of each string in the arrays
     local -A keyword_validation
     keyword_validation[name]=' 
@@ -125,7 +142,7 @@ function initialise {
         pre_hook 
         shutdown 
     '
-    keyword_validation[repeat invalid]=' 
+    keyword_validation[repeat_invalid]=' 
         checkhotplugusage 
         organisationname 
         post_hook 
@@ -133,7 +150,10 @@ function initialise {
         shutdown 
     '
     local +r keyword_validation
+    hotplugdevice_keyword_found_flag=$false
     parse_conf "$conf_fn"
+    [[ ! $checkhotplugusage_keyword_found_flag ]] && emsg+=$msg_lf"Keyword 'Check hotplug usage' is required"
+    [[ $wmsg != '' ]] && msg W "Error(s) in configuration file $conf_fn:$wmsg"
     [[ $emsg != '' ]] && msg E "Error(s) in configuration file $conf_fn:$emsg"
 
     # Postprocess and error trap the configuration
@@ -143,6 +163,12 @@ function initialise {
     if [[ ! $subsidiary_mode_flag ]]; then
         postprocess_email_for_report
         err_trap_email_for_report
+    fi
+
+    # Check hotplug usage
+    if [[ $checkhotplugusage_keyword_found_flag ]]; then
+        postprocess_checkhotplugusage_conf
+        err_trap_checkhotplugusage_conf
     fi
 
     # Log retention
@@ -166,13 +192,6 @@ function initialise {
     # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     [[ $conf_check_flag ]] \
         && { msg I "Configuration check OK for $conf_fn"; finalise 0; }
-
-    [[ $emsg != '' ]] && msg E "Error(s) in configuration file $conf_fn:$emsg"
- 
-    # Finish if -C option (check the configuration)
-    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    [[ $conf_check_flag ]] \
-        && { msg I "Configuration check OK for $conf_fn"; finalise 0; }
  
     # Create and lock the PID file
     # ~~~~~~~~~~~~~~~~~~~~~~~~~~
@@ -182,7 +201,6 @@ function initialise {
 }  # end of function initialise
 
 source "$BUNG_LIB_DIR/msg.fun" || exit 1
-source "$BUNG_LIB_DIR/my_cat.fun" || exit 1
 source "$BUNG_LIB_DIR/parse_conf.fun" || exit 1
 
 #--------------------------
@@ -191,92 +209,124 @@ source "$BUNG_LIB_DIR/parse_conf.fun" || exit 1
 # Arguments: none
 # Global variable usage:
 #   Read:
-#       * ck_hotplug_usage_org[]
-#       * ck_hotplug_usage_email[]
-#       * ck_hotplug_usage_max_backup_age[]
-#       * ck_hotplug_usage_max_device_change_days[]
+#       * ck_hotplug_usage_org
+#       * ck_hotplug_usage_email
+#       * ck_hotplug_usage_max_backup_age
+#       * ck_hotplug_usage_max_device_change_days
 # Return code: always 0; does not return on error
 #--------------------------
 function ck_hotplug_usage {
     fct "${FUNCNAME[0]}" 'started'
-    local array buf date_now hotplug_usage_log_fn i last_line_flag last_serial msg msgs serial
+    local buf msg
+    local date_now hotplug_usage_log_fn last_line_flag last_serial lines serial
     local usage_org usage_emails
-    local usage_max_backup_age_days usage_max_backup_age_secs
-    local usage_max_device_change_days usage_max_device_change_secs
+    local usage_max_backup_age_secs usage_max_device_change_secs
 
-    # Nothing to do?
-    # ~~~~~~~~~~~~~~
-    if ((ck_hotplug_usage_idx==-1)); then
-        msg I "No 'Check organisation name' configured in $conf_fn"
-        return
+    # Get the usage log file name
+    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+    date_now=$(date +%s)
+    usage_org=$ck_hotplug_usage_org
+    hotplug_usage_log_fn=$log_dir/hotplug/$ck_hotplug_usage_org
+    msg I "Checking $hotplug_usage_log_fn"
+    buf=$(ck_file "$hotplug_usage_log_fn" f:r 2>&1)
+    if [[ $buf != '' ]]; then
+        msg E "Hotplug usage log: $buf"
     fi
 
-    # For each organisation
+    # Check the log content
     # ~~~~~~~~~~~~~~~~~~~~~
-    date_now=$(date +%s)
-    for ((i=0;i<=ck_hotplug_usage_idx;i++))
+    usage_max_backup_age_secs=$((ck_hotplug_usage_max_backup_age*24*60*60))
+    usage_max_device_change_secs=$((ck_hotplug_usage_max_device_change_days*24*60*60))
+    last_line_flag=$true
+    lines=
+    while read -r date serial
     do
-        msgs=
-        usage_org=${ck_hotplug_usage_org[i]}
-        msg I "Checking $usage_org"
-        hotplug_usage_log_fn=$BUNG_LOG_DIR/hotplug/$usage_org
-        buf=$(ck_file "$hotplug_usage_log_fn" f:r 2>&1)
-        if [[ $buf != '' ]]; then
-            msg W "Hotplug usage log: $buf"
-            continue
-        fi
-
-        # For each line of the log
-        # ~~~~~~~~~~~~~~~~~~~~~~~~
-        usage_max_backup_age_days=${ck_hotplug_usage_max_backup_age[i]}
-        usage_max_backup_age_secs=$((usage_max_backup_age_days*24*60*60))
-        usage_max_device_change_days=${ck_hotplug_usage_max_device_change_days[i]}
-        usage_max_device_change_secs=$((usage_max_device_change_days*24*60*60))
-        last_line_flag=$true
-        while read -r date serial
-        do
-            # Last backup too long ago?
-            # ~~~~~~~~~~~~~~~~~~~~~~~~~
-            if [[ $last_line_flag ]]; then    # Last line of log only
-                last_line_flag=$false
-                if ((date_now-$(date --date=$date +%s)>usage_max_backup_age_secs)); then
-                    msg="The last backup of $usage_org was $usage_max_backup_age_days or more days ago on $date"
-                    msg W "$msg"
-                    msgs+=$msg_lf$msg
-                fi
-                last_serial=$serial
-            else
-                if [[ $last_serial != $serial ]]; then    # Last hotplug device change
-                    if ((date_now-$(date --date=$date +%s)>usage_max_device_change_secs)); then
-                        msg="The last backup of $usage_org on a different hotplug device was $usage_max_device_change_days or more days ago on $date"
-                        msg W "$msg"
-                        msgs+=$msg_lf$msg
-                    fi
-                    break
-                fi
+        lines+=$'\n'"$date $serial"
+        # Last backup too long ago?
+        # ~~~~~~~~~~~~~~~~~~~~~~~~~
+        if [[ $last_line_flag ]]; then    # Last line of log only
+            last_line_flag=$false
+            if ((date_now-$(date --date=$date +%s)>usage_max_backup_age_secs)); then
+                msg="The last hotplug backup of $usage_org was $ck_hotplug_usage_max_backup_age or more days ago on $date"
+                break
             fi
-        done <<< "$(tac "$hotplug_usage_log_fn")"
-
-        # Final messaging for this organisation
-        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-        if [[ $msgs = '' ]]; then
-            msg I 'No problems found'
+            last_serial=$serial
         else
-            echo "$msgs" \
-                | mailx -s 'Problems detected with backup to hotplug storage' \
-                     ${ck_hotplug_usage_email[i]}
+            if [[ $last_serial != $serial ]]; then    # Last hotplug device change
+                if ((date_now-$(date --date=$date +%s)>usage_max_device_change_secs)); then
+                    msg="The last backup of $usage_org on a different hotplug device was $ck_hotplug_usage_max_device_change_days or more days ago on $date"
+                fi
+                break
+            fi
         fi
-    done
+    done <<< "$(tac "$hotplug_usage_log_fn")"
+
+    # Final messaging for this organisation
+    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+    if [[ ${msg:-} = '' ]]; then
+        msg I 'No problems found'
+    else
+        msg+=$'\n'"Relevant lines from $hotplug_usage_log_fn:"$lines
+        msg I "$msg"
+        cmd=(my_mailx -a "$ck_hotplug_usage_email" -b "$msg" -s 'Problems detected with backup to hotplug storage')
+        "${cmd[@]}"
+    fi
 
     fct "${FUNCNAME[0]}" 'returning'
     return
 }  # end of function ck_hotplug_usage
 
 #--------------------------
-# Name: parse_conf_ck_hotplug_usage
+# Name: err_trap_checkhotplugusage_conf
+# Purpose:
+#   Error traps the "Check hotplug usage" subkeywords
+# Arguments: none
+# Global variable usage: adds any error message to emsg, prefixed by $msg_lf
+# Output: none
+# Return value: 1 when an error is detected, 0 otherwise
+#--------------------------
+function err_trap_checkhotplugusage_conf {
+    fct "${FUNCNAME[0]}" 'started'
+    local i my_rc oIFS old_emsg
+    local -r email_address_re='^[A-Za-z0-9._%+-]+(@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})?$'
+
+    # Initialise
+    # ~~~~~~~~~~
+    old_emsg=$emsg
+    emsg=
+    my_rc=0
+
+    # Error traps
+    # ~~~~~~~~~~~
+    [[ $ck_hotplug_usage_org = '' ]] && emsg+=$msg_lf'Subkeyword Organisation is required'
+
+    # Function parse_conf_subkey_value appends any Email values found to $ck_hotplug_usage_email prefixed with a ","
+    if [[ ${ck_hotplug_usage_email:-} != '' ]]; then
+        ck_hotplug_usage_email=${ck_hotplug_usage_email#,}
+        oIFS=$IFS
+        IFS=,
+        for buf in $ck_hotplug_usage_email
+        do
+            [[ ! $buf =~ $email_address_re ]] && emsg+=$msg_lf"Invalid email address $buf"
+        done
+    fi
+    IFS=$oIFS
+
+    err_trap_uint "$maxbackupage" "Invalid MaxBackupAge '$maxbackupage'"
+    err_trap_uint "$maxdevicechangedays" "Invalid MaxDeviceChangeDays '$maxdevicechangedays'"
+
+    [[ $emsg != '' ]] && my_rc=1
+    emsg=$old_emsg$emsg
+    fct "${FUNCNAME[0]}" "returning, rc $my_rc"
+    return $my_rc
+}  # end of function err_trap_checkhotplugusage_conf
+
+source "$BUNG_LIB_DIR/my_mailx.fun" || exit 1
+
+#--------------------------
+# Name: parse_conf_checkhotplugusage
 # Purpose:
 #   Parses a "Check hotplug usage" line from the configuration file
-#   Note: does not error trap sub-values
 # Arguments:
 #   $1 - the keyword as read from the configuration file (not normalised)
 #   $2 - the value from the configuration file
@@ -287,40 +337,48 @@ function ck_hotplug_usage {
 #       line_n
 #       true
 #   Set:
-#       ck_hotplug_usage_idx incremented
 #       pc_emsg appended with any error message
 # Output: none except via function fct
 # Return value:
 #   0 when no error detected
 #   1 when an error is detected
 #--------------------------
-function parse_conf_ck_hotplug_usage {
+function parse_conf_checkhotplugusage {
     fct "${FUNCNAME[0]}" "started with keyword: ${1:-}, value:${2:-}"
     local buf initial_pc_emsg my_rc
 
     # Parse arguments
     # ~~~~~~~~~~~~~~~
-    if [[ ${3:-} != '' ]]; then
-        msg="Programmming error: ${FUNCNAME[0]} called with a third argument"
+    if (($#!=3)); then
+        msg="Programmming error: ${FUNCNAME[0]} called with $# arguments instead of 3"
         msg E "$msg (args: $*)"
     fi
     local -r keyword=$1
-    unparsed_str=$2
+    local -r value=$2
+    local -r line_n=$3
 
     # Initialise
     # ~~~~~~~~~~
-    ck_hotplug_usage_org[++ck_hotplug_usage_idx]=
-    ck_hotplug_usage_email[ck_hotplug_usage_idx]=
-    ck_hotplug_usage_max_backup_age[ck_hotplug_usage_idx]=
-    ck_hotplug_usage_max_device_change_days[ck_hotplug_usage_idx]=
-    ck_hotplug_usage_org[ck_hotplug_usage_idx]=
-    initial_pc_emsg=$pc_emsg
+    local -r initial_pc_emsg=$pc_emsg
+    unparsed_str=$value
+
+    # Initialise
+    # ~~~~~~~~~~
+    ck_hotplug_usage_email=
+    ck_hotplug_usage_max_backup_age=3
+    ck_hotplug_usage_max_device_change_days=3
+    ck_hotplug_usage_org=
+
+    # Note that a 'Check hotplug usage' keyword was found in the conffile
+    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+    # This function is only called when function parse_conf finds a 'Check hotplug usage' keyword
+    checkhotplugusage_keyword_found_flag=$true
 
     # Parse any subkeywords
     # ~~~~~~~~~~~~~~~~~~~~~
     # Syntax:
     # Check hotplug usage = Organisation=<organisation name>
-    #     [Email=<email address>] [MaxBackupAge=<days>]
+    #     [Email=<email address> ...] [MaxBackupAge=<days>]
     #     [MaxDeviceChangeDays=<days>]
     # Note: ensure a space on both sides of each string in the arrays
     local -A subkey_validation
@@ -330,49 +388,57 @@ function parse_conf_ck_hotplug_usage {
         maxdevicechangedays 
         organisation 
     '
-    subkey_validation[value required]='
+    subkey_validation[value_required]='
         email
         maxbackupage 
         maxdevicechangedays 
         organisation 
     '
-    subkey_validation[value invalid]=' '
+    subkey_validation[value_invalid]=' '
     local +r subkey_validation
     while [[ $unparsed_str != '' ]]
     do
        parse_conf_subkey_value "${FUNCNAME[0]}" $line_n
     done
 
-    # Remove any leading "," from the email(s) value
-    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    ck_hotplug_usage_email[ck_hotplug_usage_idx]=${ck_hotplug_usage_email[ck_hotplug_usage_idx]:1}
-
-    # Set defaults if not configured
-    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    if [[ ${ck_hotplug_usage_email[ck_hotplug_usage_idx]} = '' ]]; then
-        ck_hotplug_usage_email[ck_hotplug_usage_idx]=root
-    fi
-    if [[ ${ck_hotplug_usage_max_backup_age[ck_hotplug_usage_idx]} = '' ]]; then
-        ck_hotplug_usage_max_backup_age[ck_hotplug_usage_idx]=3
-    fi
-    if [[ ${ck_hotplug_usage_max_device_change_days[ck_hotplug_usage_idx]} = '' ]]; then
-        ck_hotplug_usage_max_device_change_days[ck_hotplug_usage_idx]=3
-    fi
-
     # Error trap Organisation not given
     # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    if [[ ${ck_hotplug_usage_org[ck_hotplug_usage_idx]} = '' ]]; then
+    if [[ $ck_hotplug_usage_org = '' ]]; then
         pc_emsg+=$msg_lf"Organisation sub-keyword is required (line $line_n)"
     fi
 
     [[ $pc_emsg = $pc_emsg ]] && my_rc=0 || my_rc=1
     fct "${FUNCNAME[0]}" "returning with rc $my_rc"
     return $my_rc
-}  # end of function parse_conf_ck_hotplug_usage
+}  # end of function parse_conf_checkhotplugusage
 
+source "$BUNG_LIB_DIR/parse_conf_word.fun" || exit 1
 source "$BUNG_LIB_DIR/parse_conf_subsidiaryscript.fun" || exit 1
 source "$BUNG_LIB_DIR/postprocess_email_for_report.fun" || exit 1
 source "$BUNG_LIB_DIR/postprocess_org_name_conf.fun" || exit 1
+
+#--------------------------
+# Name: postprocess_checkhotplugusage_conf
+# Purpose:
+#   Postprocesses the "Check hotplug usage" subkeywords
+# Arguments: none
+# Global variable usage: adds any error message to emsg, prefixed by $msg_lf
+# Output: none
+# Return value: 1 when an error is detected, 0 otherwise
+#--------------------------
+function postprocess_checkhotplugusage_conf {
+    fct "${FUNCNAME[0]}" 'started'
+
+    # Set default Email value
+    # ~~~~~~~~~~~~~~~~~~~~~~~
+    # This cannot be unsurprisingly defaulted by parse_conf_checkhotplugusage like the other subkeyword values
+    # because function parse_conf_subkey_value appends any Email values to $ck_hotplug_usage_email prefixed with a ","
+    [[ ${ck_hotplug_usage_email:-} = '' ]] && ck_hotplug_usage_email=root
+
+    fct "${FUNCNAME[0]}" 'returning 0'
+    return 0
+}  # end of function postprocess_checkhotplugusage_conf
+
 source "$BUNG_LIB_DIR/run_pre_hooks.fun" || exit 1
 source "$BUNG_LIB_DIR/usage.fun" || exit 1
 
diff --git a/source/usr/bin/sysinfo_bu b/source/usr/bin/sysinfo_bu
--- a/source/usr/bin/sysinfo_bu
+++ b/source/usr/bin/sysinfo_bu
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-# Copyright (C) 2022 Charles Atkinson
+# Copyright (C) 2023 Charles Atkinson
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -17,8 +17,7 @@
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 
 # Purpose:
-#   Runs a variety of system information generating tools as part of the
-#   Backup Next Generation (bung) suite
+#   Runs a variety of system information generating tools as part of the Backup Next Generation (bung) suite
 
 # Usage:
 #   See usage.fun or use -h option.
@@ -79,6 +78,8 @@ source "$BUNG_LIB_DIR/version.scrippet" || exit 1
 #    |   +-- err_trap_pre_hook_conf
 #    |   |
 #    |   +-- err_trap_sysinfo_conf
+#    |   |   |
+#    |   |   +-- err_trap_retention
 #    |   |
 #    |   +-- err_trap_shutdown
 #    |   |
@@ -131,6 +132,8 @@ source "$BUNG_LIB_DIR/version.scrippet" || exit 1
 #    |   +-- report_dest_dir_usage
 #    |
 #    +-- finalise
+#        |
+#        +-- functions as documented in finalise.fun
 #
 # Utility functions called from various places:
 #     ck_file ck_uint do_umounts err_trap_uint fct msg parse_conf_subkey_value
@@ -145,13 +148,39 @@ source "$BUNG_LIB_DIR/do_snapshots.fun" || exit 1
 source "$BUNG_LIB_DIR/do_umounts.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_email_for_report.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_mount_conf.fun" || exit 1
+source "$BUNG_LIB_DIR/err_trap_notification_plug_in_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_post_hook_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_pre_hook_conf.fun" || exit 1
+source "$BUNG_LIB_DIR/err_trap_retention_conf.fun" || exit 1
+
+#--------------------------
+# Name: err_trap_sysinfo_files_and_dirs
+# Purpose: error traps sysinfo-specific files and directories
+# Arguments: none
+# Return code: always 0; does not return on error
+#--------------------------
+function err_trap_sysinfo_files_and_dirs {
+    fct "${FUNCNAME[0]}" 'started'
+    local buf i
+    local my_emsg=
+
+    buf=$(ck_file "$dest_dir" d:rwx 2>&1)
+    if [[ $buf != '' ]]; then
+        my_emsg+=$msg_lf$buf
+    fi
+
+    if [[ $my_emsg != '' ]]; then
+        msg E "File and/or directory problems:$my_emsg"
+    fi
+
+    fct "${FUNCNAME[0]}" 'returning'
+    return
+}  # end of function err_trap_sysinfo_files_and_dirs
 
 #--------------------------
 # Name: err_trap_sysinfo_conf
 # Purpose:
-#   Error traps the sysinfo_bu-specific configuration
+#   Error traps sysinfo sub-keywords other than dest_dir which may be on a yet to be mounted file system
 # Arguments: none
 # Global variable usage: adds any error message to emsg, prefixed by $msg_lf
 # Output: none
@@ -167,11 +196,14 @@ function err_trap_sysinfo_conf {
     emsg=
     my_rc=0
 
-    # Nothing to do?
-    # ~~~~~~~~~~~~~~
-    if ((sysinfo_idx<0)); then
-        emsg+=$msg_lf"No backup configured (no sysinfo keyword)"
-    fi
+    # Trap errors
+    # ~~~~~~~~~~~
+    buf=$dest_dir_usage_warning
+    err_trap_uint "$buf" "Invalid dest_dir_usage_warning" \
+        && ((buf>100)) \
+        && emsg+=$msg_lf"Invalid dest_dir_usage_warning % $buf (maximum 100)"
+
+    err_trap_retention_conf "$retention"
 
     [[ $emsg != '' ]] && my_rc=1
     emsg=$old_emsg$emsg
@@ -179,37 +211,6 @@ function err_trap_sysinfo_conf {
     return $my_rc
 }  # end of function err_trap_sysinfo_conf
 
-#--------------------------
-# Name: err_trap_sysinfo_files_and_dirs
-# Purpose: error traps sysinfo-specific files and directories
-# Arguments: none
-# Return code: always 0; does not return on error
-#--------------------------
-function err_trap_sysinfo_files_and_dirs {
-    fct "${FUNCNAME[0]}" 'started'
-    local buf i
-    local my_emsg=
-
-    # For each configured rsync job
-    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    for ((i=0;i<=sysinfo_idx;i++))
-    do
-        buf=$(ck_file "${dest_dirs[i]}" d:rwx 2>&1)
-        if [[ $buf != '' ]]; then
-            my_emsg+=$msg_lf$buf
-        fi
-    done
-
-    if [[ $my_emsg != '' ]]; then
-        msg E "File and/or directory problems:$my_emsg"
-    fi
-
-    fct "${FUNCNAME[0]}" 'returning'
-    return
-}  # end of function err_trap_sysinfo_files_and_dirs
-
-source "$BUNG_LIB_DIR/err_trap_shutdown.fun" || exit 1
-source "$BUNG_LIB_DIR/err_trap_snapshot_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_uint.fun" || exit 1
 source "$BUNG_LIB_DIR/fct.fun" || exit 1
 source "$BUNG_LIB_DIR/finalise.fun" || exit 1
@@ -433,7 +434,7 @@ function get_hdd_and_sdd_info {
 
     # Get smartctl version
     # ~~~~~~~~~~~~~~~~~~~~
-    # Versions listed at https://www.smartmontools.org/wiki/News 
+    # Versions listed at https://www.smartmontools.org/wiki/News
     smartctl_out=$(smartctl --version 2>&1)
     if [[ $smartctl_out =~ $smartctl_out_regex ]]; then
         array=($smartctl_out)
@@ -500,7 +501,7 @@ source "$BUNG_LIB_DIR/get_fs_type.fun" || exit 1
 #--------------------------
 # Name: get_groups_n_user_info
 # Purpose: gets groups and user information
-# Arguments: $1 index into sysinfo_ arrays
+# Arguments: none
 # Return code: always 0; does not return on error
 #--------------------------
 function get_groups_n_user_info {
@@ -508,7 +509,6 @@ function get_groups_n_user_info {
     local all_groups group_list unwanted_groups
     local all_users user_list unwanted_users
     local cmd i
-    local -r idx=$1
 
     echo $'\n'"**** GROUPS AND USERS ****" >> "$my_out_fn" || finalise 1
 
@@ -572,12 +572,12 @@ function get_hw_info {
     # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     [[ $platform = hardware ]] && cmds+=(
         'dmidecode --type 2'
-        "get_hdd_and_sdd_info $1"
+        "get_hdd_and_sdd_info"
     )
     cmds+=(
         'cat /proc/cpuinfo'
-        "get_mem_info $1"
-        "get_eth_hw_info $1"
+        "get_mem_info"
+        "get_eth_hw_info"
     )
 
     # Run the available commands
@@ -826,13 +826,12 @@ function get_network_info {
 #--------------------------
 # Name: get_package_info
 # Purpose: gets package information
-# Arguments: $1 index into sysinfo_ arrays
+# Arguments: none
 # Return code: always 0; does not return on error
 #--------------------------
 function get_package_info {
     fct "${FUNCNAME[0]}" 'started'
     local cmd in_fn
-    local -r idx=$1
 
     echo $'\n'"**** PACKAGES ****" >> "$my_out_fn" || finalise 1
 
@@ -876,7 +875,7 @@ function get_package_info {
 #--------------------------
 # Name: get_storage_info
 # Purpose: gets storage information
-# Arguments: $1 index into sysinfo_ arrays
+# Arguments: none
 # Return code: always 0; does not return on error
 #--------------------------
 function get_storage_info {
@@ -885,7 +884,6 @@ function get_storage_info {
     local -r dos_part_lister=fdisk
     local -r fdisk_gpt_regex='Disklabel type: gpt|WARNING: GPT'
     local -r fdisk_unpartitioned_regex="doesn't contain a valid partition table"
-    local -r idx=$1
     local -r loop_regex='^/dev/loop'
     local -r part_lister_out_OK_regex='(^$|does not start on physical sector boundary)'
     local -r vgs_regex='^[[:space:]]+VG[[:space:]]+#PV[[:space:]]+#LV[[:space:]]+#SN[[:space:]]+Attr[[:space:]]+VSize[[:space:]]+VFree'
@@ -1079,12 +1077,12 @@ function initialise {
 
     # Parse configuration file
     # ~~~~~~~~~~~~~~~~~~~~~~~~
-    emsg=
     local -A keyword_validation
     keyword_validation[name]='
         emailforreport
         logretention
         mount
+        notificationplug_in 
         organisationname
         post_hook
         pre_hook
@@ -1092,7 +1090,7 @@ function initialise {
         shutdown
         snapshot
     '
-    keyword_validation[repeat invalid]='
+    keyword_validation[repeat_invalid]='
         logretention
         organisationname
         post_hook
@@ -1101,7 +1099,9 @@ function initialise {
         shutdown
     '
     local +r keyword_validation
+    sysinfo_keyword_found_flag=$false
     parse_conf "$conf_fn"
+    [[ ! $sysinfo_keyword_found_flag ]] && emsg+=$msg_lf"Keyword sysinfo is required"
     [[ $emsg != '' ]] && msg E "Error(s) in configuration file $conf_fn:$emsg"
 
     # Postprocess and error trap the configuration
@@ -1119,6 +1119,9 @@ function initialise {
     # Mount
     postprocess_mount_conf
     err_trap_mount_conf
+
+    # Notification plug-in
+    err_trap_notification_plug_in_conf
 
     # Organisation name
     postprocess_org_name_conf "${org_name:-}" "${org_name_optarg:-}" "$opt_o_flag"
@@ -1138,6 +1141,7 @@ function initialise {
     # Snapshot
     postprocess_snapshot_conf && err_trap_snapshot_conf
 
+    [[ $wmsg != '' ]] && msg W "Error(s) in configuration file $conf_fn:$wmsg"
     [[ $emsg != '' ]] && msg E "Error(s) in configuration file $conf_fn:$emsg"
 
     # Finish if -C option (check the configuration)
@@ -1157,7 +1161,7 @@ function initialise {
 }  # end of function initialise
 
 source "$BUNG_LIB_DIR/msg.fun" || exit 1
-source "$BUNG_LIB_DIR/my_cat.fun" || exit 1
+source "$BUNG_LIB_DIR/my_mailx.fun" || exit 1
 source "$BUNG_LIB_DIR/parse_conf.fun" || exit 1
 
 #--------------------------
@@ -1174,7 +1178,6 @@ source "$BUNG_LIB_DIR/parse_conf.fun" || exit 1
 #       true and false
 #       line_n
 #   Set:
-#       sysinfo_idx incremented
 #       pc_emsg appended with any error message
 # Output: none except via function fct
 # Return value:
@@ -1183,7 +1186,7 @@ source "$BUNG_LIB_DIR/parse_conf.fun" || exit 1
 #--------------------------
 function parse_conf_sysinfo {
     fct "${FUNCNAME[0]}" "started with keyword: ${1:-}, value: ${2:-}, line_n: ${3:-}"
-    local buf dest idx msg my_rc src
+    local buf dest msg my_rc src
 
     # Parse arguments
     # ~~~~~~~~~~~~~~~
@@ -1200,29 +1203,34 @@ function parse_conf_sysinfo {
     local -r initial_pc_emsg=$pc_emsg
     unparsed_str=$value
 
+    # Note that a sysinfo keyword was found in the conffile
+    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+    # This function is only called when function parse_conf finds a sysinfo keyword
+    sysinfo_keyword_found_flag=$true
+
     # Set sub-keyword default values
     # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    idx=$((++sysinfo_idx))
-    dest_dirs[idx]=/var/backup/sysinfo
-    dest_dir_usage_warnings[idx]=80
-    backup_retention[idx]=28
+    dest_dir=/var/backup/sysinfo
+    dest_dir_usage_warning=80
+    retention=28
 
     # Get any sub-keyword values
     # ~~~~~~~~~~~~~~~~~~~~~~~~~~
-    # The value format/syntax is one of:
-    #   sysinfo = [dest_dir=dir] [dest_dir_usage_warning=%] [retention=days]
+    # Syntax:
+    #   sysinfo = [dest_dir=<dir>] [dest_dir_usage_warning=<%>]
+    #       [retention=<number>[days]]|0[days]]|<number>percent_usage[,<number>min_old_backups]|<number>old_backups]
     local -A subkey_validation
     subkey_validation[name]='
         dest_dir
         dest_dir_usage_warning
         retention
     '
-    subkey_validation[value required]='
+    subkey_validation[value_required]='
         dest_dir
         dest_dir_usage_warning
         retention
     '
-    subkey_validation[value invalid]=' '
+    subkey_validation[value_invalid]=' '
     local +r subkey_validation
     while [[ $unparsed_str != '' ]]
     do
@@ -1240,9 +1248,13 @@ source "$BUNG_LIB_DIR/postprocess_email_for_report.fun" || exit 1
 source "$BUNG_LIB_DIR/postprocess_mount_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/postprocess_org_name_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/postprocess_snapshot_conf.fun" || exit 1
+source "$BUNG_LIB_DIR/remove_old_backups.fun" || exit 1
 source "$BUNG_LIB_DIR/report_dest_dir_usage.fun" || exit 1
 source "$BUNG_LIB_DIR/run_cmd_with_timeout.fun" || exit 1
+source "$BUNG_LIB_DIR/run_notification_plug_in.fun" || exit 1
 source "$BUNG_LIB_DIR/run_pre_hooks.fun" || exit 1
+source "$BUNG_LIB_DIR/err_trap_shutdown.fun" || exit 1
+source "$BUNG_LIB_DIR/err_trap_snapshot_conf.fun" || exit 1
 
 #--------------------------
 # Name: sysinfo_bu
@@ -1253,43 +1265,32 @@ source "$BUNG_LIB_DIR/run_pre_hooks.fun" || exit 1
 function sysinfo_bu {
     fct "${FUNCNAME[0]}" 'started'
     local array buf i find_pat msg_class my_out_fn
-    local dest_dir dest_dir_remote_flag dest_dir_usage_warning
+    local dest_dir_remote_flag
 
-    for ((i=0;i<=sysinfo_idx;i++))
-    do
-        # Set up the output file
-        # ~~~~~~~~~~~~~~~~~~~~~~
-        my_out_fn=${dest_dirs[i]}/sysinfo.$(date "+$fn_date_format")
-        find_pat="${dest_dirs[i]}/sysinfo.*"
+    # Set up the output file
+    # ~~~~~~~~~~~~~~~~~~~~~~
+    my_out_fn=$dest_dir/sysinfo.$(date "+$fn_date_format")
 
-        # Get each type of system information
-        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-        get_name_info $i
-        get_hw_info $i
-        get_bios_info $i
-        get_storage_info $i
-        get_network_info $i
-        get_groups_n_user_info $i
-        get_database_mysql_info $i
-        get_database_pg_info $i
-        get_package_info $i
+    # Get each type of system information
+    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+    get_name_info
+    get_hw_info
+    get_bios_info
+    get_storage_info
+    get_network_info
+    get_groups_n_user_info
+    get_database_mysql_info
+    get_database_pg_info
+    get_package_info
 
-        # Log the output file
-        # ~~~~~~~~~~~~~~~~~~~
-        msg I "The sysinfo_bu report:$msg_lf$(ls -l "$my_out_fn" 2>&1)"
+    # Log the output file
+    # ~~~~~~~~~~~~~~~~~~~
+    msg I "The sysinfo_bu report:$msg_lf$(ls -l "$my_out_fn" 2>&1)"
 
-        # Remove old backups
-        # ~~~~~~~~~~~~~~~~~~
-        find "${find_pat%/*}" -maxdepth 1 -name "${find_pat##*/}" \
-            -mtime "+${backup_retention[i]}" -execdir rm {} \;
-
-        # Log the destination directory usage
-        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-        dest_dir=${dest_dirs[i]}
-        dest_dir_remote_flag=$false
-        dest_dir_usage_warning=${dest_dir_usage_warnings[i]}
-        report_dest_dir_usage
-    done
+    # Log the destination directory usage
+    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+    dest_dir_remote_flag=$false
+    report_dest_dir_usage
 
     fct "${FUNCNAME[0]}" 'returning'
     return
@@ -1307,5 +1308,6 @@ do_snapshots
 do_mounts
 err_trap_sysinfo_files_and_dirs
 ((pre_hook_idx>-1)) && run_pre_hooks
+remove_old_backups -m dir -n 'sysinfo.*' -s "$dest_dir"
 sysinfo_bu
 finalise 0
diff --git a/source/usr/bin/templated_bu b/source/usr/bin/templated_bu
--- a/source/usr/bin/templated_bu
+++ b/source/usr/bin/templated_bu
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-# Copyright (C) 2021 Charles Atkinson
+# Copyright (C) 2023 Charles Atkinson
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -56,6 +56,8 @@ source "$BUNG_LIB_DIR/version.scrippet" || exit 1
 #    |   +-- postprocess_templated_conf
 #    |   |
 #    |   +-- err_trap_templated_conf
+#    |   |   |
+#    |   |   +-- err_trap_retention
 #    |   |
 #    |   +-- err_trap_shutdown
 #    |   |
@@ -72,6 +74,8 @@ source "$BUNG_LIB_DIR/version.scrippet" || exit 1
 #    |   +-- get_fs_type
 #    |   |
 #    |   +-- do_mount_command
+#    |
+#    +-- remove_old_backups
 #    |
 #    +-- run_template
 #    |   |
@@ -90,6 +94,8 @@ source "$BUNG_LIB_DIR/version.scrippet" || exit 1
 #    +-- report_dest_dir_usage
 #    |
 #    +-- finalise
+#        |
+#        +-- functions as documented in finalise.fun
 #
 # Utility functions called from various places:
 #     ck_file ck_uint do_umounts err_trap_uint fct msg
@@ -210,11 +216,13 @@ source "$BUNG_LIB_DIR/do_snapshots.fun" || exit 1
 source "$BUNG_LIB_DIR/do_umounts.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_email_for_report.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_mount_conf.fun" || exit 1
+source "$BUNG_LIB_DIR/err_trap_notification_plug_in_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_post_hook_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_pre_hook_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_templated_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_shutdown.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_snapshot_conf.fun" || exit 1
+source "$BUNG_LIB_DIR/err_trap_retention_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/err_trap_uint.fun" || exit 1
 source "$BUNG_LIB_DIR/fct.fun" || exit 1
 source "$BUNG_LIB_DIR/finalise.fun" || exit 1
@@ -243,13 +251,13 @@ function initialise {
 
     # Parse configuration file
     # ~~~~~~~~~~~~~~~~~~~~~~~~
-    emsg=
     # Note: ensure a space on both sides of each string in the arrays
     local -A keyword_validation
     keyword_validation[name]='
         emailforreport 
         logretention 
         mount 
+        notificationplug_in 
         organisationname 
         post_hook 
         pre_hook 
@@ -257,7 +265,7 @@ function initialise {
         snapshot 
         templated 
     '
-    keyword_validation[repeat invalid]='
+    keyword_validation[repeat_invalid]='
         logretention 
         organisationname 
         post_hook 
@@ -266,7 +274,9 @@ function initialise {
         templated 
 '
     local +r keyword_validation
+    templated_keyword_found_flag=$false
     parse_conf "$conf_fn"
+    [[ ! $templated_keyword_found_flag ]] && emsg+=$msg_lf"Keyword templated is required"
     [[ $emsg != '' ]] && msg E "Error(s) in configuration file $conf_fn:$emsg"
 
     # Postprocess and error trap the configuration
@@ -295,6 +305,9 @@ function initialise {
     postprocess_mount_conf
     err_trap_mount_conf
 
+    # Notification plug-in
+    err_trap_notification_plug_in_conf
+
     # Organisation name
     postprocess_org_name_conf "${org_name:-}" "${org_name_optarg:-}" "$opt_o_flag"
 
@@ -305,12 +318,15 @@ function initialise {
     err_trap_pre_hook_conf
 
     # templated
-    postprocess_templated_conf
-    err_trap_templated_conf
+    if [[ $templated_keyword_found_flag ]]; then
+        postprocess_templated_conf
+        err_trap_templated_conf
+    fi
 
     # Snapshot
     postprocess_snapshot_conf && err_trap_snapshot_conf
 
+    [[ $wmsg != '' ]] && msg W "Error(s) in configuration file $conf_fn:$wmsg"
     [[ $emsg != '' ]] && msg E "Error(s) in configuration file $conf_fn:$emsg"
 
     # Finish if -C option (check the configuration)
@@ -340,9 +356,8 @@ function initialise {
 }  # end of function initialise
 
 source "$BUNG_LIB_DIR/msg.fun" || exit 1
-source "$BUNG_LIB_DIR/my_cat.fun" || exit 1
+source "$BUNG_LIB_DIR/my_mailx.fun" || exit 1
 source "$BUNG_LIB_DIR/parse_conf.fun" || exit 1
-source "$BUNG_LIB_DIR/parse_conf_templated.fun" || exit 1
 source "$BUNG_LIB_DIR/parse_conf_word.fun" || exit 1
 
 #--------------------------
@@ -455,87 +470,119 @@ function parse_conf_line_data {
     return 0
 }  # end of function parse_conf_line_data
 
+#--------------------------
+# Name: parse_conf_templated
+# Purpose:
+#   Parses a templated line from the configuration file
+#   Note: does not error trap sub-values, only traps syntactical errors
+# Arguments:
+#   $1 - the keyword as read from the configuration file (not normalised)
+#   $2 - the value from the configuration file
+# Global variable usage:
+#   Read:
+#       false
+#       line_n
+#       true
+#   Set:
+#       pc_emsg appended with any error message
+# Output: none except via function fct
+# Return value:
+#   0 when no error detected
+#   1 when an error is detected
+#--------------------------
+function parse_conf_templated {
+    fct "${FUNCNAME[0]}" "started with keyword: ${1:-}, value: ${2:-}, line_n: ${3:-}"
+    local buf dest msg my_rc src unparsed_str
+
+    # Parse arguments
+    # ~~~~~~~~~~~~~~~
+    if (($#!=3)); then
+        msg="Programmming error: ${FUNCNAME[0]} called with $# arguments instead of 3"
+        msg E "$msg (args: $*)"
+    fi
+    local -r keyword=$1
+    local -r value=$2
+    local -r line_n=$3
+
+    # Initialise
+    # ~~~~~~~~~~
+    local -r initial_pc_emsg=$pc_emsg
+    unparsed_str=$value
+
+    # Note that a templated keyword was found in the conffile
+    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+    # This function is only called when function parse_conf finds a templated keyword
+    templated_keyword_found_flag=$true
+
+    # Set sub-keyword default values
+    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+    dest_dir_usage_warning=80
+    retention=28
+    templated_timeout=10
+
+    # Parse the subkeywords
+    # ~~~~~~~~~~~~~~~~~~~~~
+    # The syntax (any subkeyword order accepted) is:
+    #   templated =
+    #       template=<file>
+    #       [hostname=<FQDN>] [identity_file=<file>] [password=<password>] [username=<name>]
+    #       [device_type=<device type>]
+    #       [[dest_dir=<dir>] [dest_dir_usage_warning=<%>] [retention=...]]
+    #       [git_root=<dir>]
+    #       [tftp_root=<dir>] [tftp_server=<FQDN or IP address>]
+    #       [timeout=<duration>]
+    local -A subkey_validation
+    subkey_validation[name]='
+        dest_dir
+        dest_dir_usage_warning
+        device_type
+        git_root
+        hostname
+        identity_file
+        retention
+        password
+        template
+        tftp_root
+        tftp_server
+        timeout
+        username
+    '
+    subkey_validation[value_required]='
+        dest_dir
+        dest_dir_usage_warning
+        device_type
+        git_root
+        hostname
+        identity_file
+        password
+        retention
+        template
+        tftp_root
+        tftp_server
+        timeout
+        username
+    '
+    subkey_validation[value_invalid]=
+    local +r subkey_validation
+
+    templated_timeout=10
+    while [[ $unparsed_str != '' ]]
+    do
+       parse_conf_subkey_value "${FUNCNAME[0]}" $line_n
+    done
+    unset unparsed_str
+
+    [[ $pc_emsg = $initial_pc_emsg ]] && my_rc=0 || my_rc=1
+    fct "${FUNCNAME[0]}" "returning with rc $my_rc"
+    return $my_rc
+}  # end of function parse_conf_templated
+
 source "$BUNG_LIB_DIR/postprocess_email_for_report.fun" || exit 1
 source "$BUNG_LIB_DIR/postprocess_mount_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/postprocess_org_name_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/postprocess_templated_conf.fun" || exit 1
 source "$BUNG_LIB_DIR/postprocess_snapshot_conf.fun" || exit 1
-
-#--------------------------
-# Name: remove_old_backups
-# Purpose: checked the output from the rsync command; decides if it was OK
-# Arguments: none
-# Global variable usage:
-#   backup_dir_absolute: read
-#   backup_retention: read
-#   backup_subdir_regex: read
-#   dest_dir_remote_flag: read
-#   dest_dir_remote_host: read
-#   i (function backup's rsync_idx loop variable): read
-#   rsync_backup_dir: read
-#   rsync_cmd_ran_OK_flag: set
-#   rsync_out: read
-#   rsync_rc: read and set
-# Return code: always 0
-#--------------------------
-function remove_old_backups {
-    fct "${FUNCNAME[0]}" 'started'
-    local buf j
-    local remove_old_cmd remove_empty_cmd
-    local msg_part OK_to_continue old_PWD out
-    local remote_out remote_conf_fn
-    local -r tmp_fn=$tmp_dir/${FUNCNAME[0]}
-
-    # Nothing to do?
-    # ~~~~~~~~~~~~~~
-    if ((retention==0)); then
-        msg I "Not removing old files under $dest_dir (retention is 0)"
-        fct "${FUNCNAME[0]}" 'returning'
-        return 0
-    fi
-
-    # Remove old files
-    # ~~~~~~~~~~~~~~~~
-    msg I "Removing old files under $dest_dir"
-    remove_old_cmd=(
-        find
-        "${dest_dir:-UNSET-GUARD}"
-        -type f
-        -mtime +$((retention-1))
-        -execdir rm {} +
-    )
-    msg D "${FUNCNAME[0]}: remove_old_cmd: ${remove_old_cmd[*]}"
-    buf=$("${remove_old_cmd[@]}" 2>&1)
-    if [[ $buf = '' ]]; then
-
-        # Remove empty directories
-        # ~~~~~~~~~~~~~~~~~~~~~~~~
-        msg I "Removing empty directories under $dest_dir"
-        remove_empty_cmd=(
-            find
-            "${dest_dir:-UNSET-GUARD}"
-            -depth -mindepth 1
-            -type d
-            -empty -delete
-        )
-        msg D "${FUNCNAME[0]}: remove_empty_cmd: ${remove_empty_cmd[*]}"
-        buf=$("${remove_empty_cmd[@]}" 2>&1)
-        if [[ $buf != '' ]]; then
-            msg_part=$'\nCommand:\n'
-            msg_part+=${remove_empty_cmd[*]}
-            msg_part+=$'\nOutput:\n'
-            msg W "$msg_part$buf"
-        fi
-    else
-        msg_part=$'\nCommand:\n'
-        msg_part+=${remove_old_cmd[*]}
-        msg_part+=$'\nOutput:\n'
-        msg W "$msg_part$buf"
-    fi
-
-    fct "${FUNCNAME[0]}" 'returning'
-}  # end of function remove_old_backups
-
+source "$BUNG_LIB_DIR/remove_old_backups.fun" || exit 1
 source "$BUNG_LIB_DIR/report_dest_dir_usage.fun" || exit 1
 
 #--------------------------
@@ -570,7 +617,7 @@ function run_command {
     # * Library function parse_conf_templated
     #   * Defaults templated_timeout to 10
     #   * Calls library function parse_conf_subkey_value
-    #     * Sets templated_timeout when finds subkeyword timeout 
+    #     * Sets templated_timeout when finds subkeyword timeout
     # * Local function run_template
     #   * Sets timeout_from_template when finds "Timeout: "
     # * This function sets timeout_from_template empty after use
@@ -629,7 +676,7 @@ function run_template {
     local -r OK_rc_list_line_regex='^OK rc list: '
     local -r OK_regex_line_regex='^OK regex: '
     local -r rc_list_regex='^(>|<|>=|<=|!=|==)[[:digit:]]+(,(>|<|>=|<=|!=|==)[[:digit:]]+)*$'
-    local -r reserved_varname_regex='^[[:space:]]*dest_dir[[:space:]]*='
+    local -r reserved_varname_regex='^[[:space:]]*tmp_dir[[:space:]]*='
     local -r timeout_line_regex='^Timeout: '
     local -r warning_rc_list_line_regex='^Warning rc list: '
     local -r warning_regex_line_regex='^Warning regex: '
@@ -801,6 +848,7 @@ function substitute_tokens {
     return 0
 }  # end of function substitute_tokens
 
+source "$BUNG_LIB_DIR/run_notification_plug_in.fun" || exit 1
 source "$BUNG_LIB_DIR/run_pre_hooks.fun" || exit 1
 source "$BUNG_LIB_DIR/usage.fun" || exit 1
 
@@ -813,10 +861,12 @@ initialise "${@:-}"
 do_snapshots
 do_mounts
 ((pre_hook_idx>-1)) && run_pre_hooks
+if [[ ${dest_dir:-} != '' ]]; then
+    remove_old_backups -m tree -n '*' -s "$dest_dir"
+fi
 run_template
 [[ ${git_root_dir:-} != '' ]] && do_git
 if [[ ${dest_dir:-} != '' ]]; then
-    remove_old_backups
     dest_dir_remote_flag=$false
     report_dest_dir_usage
 fi
